client_body_temp_path /tmp/nginx/client_temp;

server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
